# Cyclops port config

http:
  rootPath: /cyclops/*
  port: 9030       # Main service port
  adminPort: 9031  # Admin port for ping, healthcheck, metrics etc

  requestLog:
    console:
      enabled: false

logging:
      level: INFO

cluster:
  name: cyclops
#  numMembersPerNode: 1
#  disableMulticast: true
#  members:
#    - 172.23.250.146:5701
#    - 172.23.250.146:5702
